# Generated by Django 4.0.2 on 2022-02-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=101)),
                ('last_name', models.CharField(max_length=101)),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('date_field', models.DateField()),
            ],
        ),
    ]
